### ISSUE TITLE
Port to modern OpenGL

### ISSUE THREAD

**Issue by Sakari369** [tyt2y3/vaserenderer#1]
Hello. Vaser looks excellent. Have you thought about porting this to modern OpenGL ?
GLSL shaders ? Would make it so much easier to test this out and port to other projects also.

**Comment by tyt2y3** [comment]
I certainly have. But crossing OpenGL 3 and ES at the same time is very hard if not impossible. It requires careful architecturing and a lot of effort. I have had a plan in mind, but just don't have the time to execute. This is always the situation of any open source project. Thanks for your interest in VASEr anyway.

**Comment by Sakari369** [comment]
Yeah I understand. Thank you anyway for all your work on this subject, your writings and illustrations have really helped me understand on how this should be done. Probably implementing a subset of such line drawing myself then in OpenGL 3.3.

**Comment by ghost** [comment]
Please keep OpenGL 1 support in order to avoid planned obsolescence. It doesn't prevent you from supporting OpenGL 3.3 too but why breaking or removing features that just work and satisfy some developers? For font rendering based on shaders, JogAmp Graph UI is a nice source of inspiration. I advise you to have a look at this paper:
http://www.cg.tuwien.ac.at/research/publications/2012/ROESSLER-2012-OGLES/

**Comment by CrushedPixel** [comment]
I know I'm late, but I created a rendering-API agnostic C++ library to generate a 2D mesh from a set of points. The generated vertices can easily be sent into a modern OpenGL pipeline.
While it doesn't have all the fancy features like anti-aliasing or changing line thickness like VASEr does, it's a start, and might help others out :)

https://github.com/CrushedPixel/Polyline2D

**Comment by tyt2y3** [comment]
I recently started a reimplementation in C# and also using shaders https://github.com/tyt2y3/vaser-unity
Thank you @CrushedPixel. I will list you repo in README.
